# Generated by Django 4.0.4 on 2022-04-24 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('b', 'Borrows'), ('l', 'Lendes')], max_length=2)),
                ('status', models.CharField(choices=[('p', 'paid'), ('u', 'unpaid')], default='p', max_length=2)),
                ('date', models.TimeField()),
                ('reason', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
